FROM mcr.microsoft.com/dotnet/core/sdk:3.1

# Install dependencies for headless chromium & coverage, zstd, awscli
RUN apt update \
    && apt install --no-install-recommends -yq \
        gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 \
        libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 \
        libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 \
        libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 \
        libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates \
        fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils default-jre wget \
        apt-transport-https libzstd-dev awscli \
    && rm -rf /var/lib/apt/lists/*

# Install dotnet coverage tools
RUN dotnet tool install --global dotnet-sonarscanner || true
